apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: docker-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.3-4
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']

    - name: docker
      image: docker:20.10.8
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock

    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
