apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5678
